<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var array $page */
$page = $this->navigation()->findActive(Navigation\Sidebar::class);

/** @var \Zend\Navigation\Page\Mvc $current */
$current = $page['page'];

/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
?>

<div class="row">
    <div class="col-sm-12">
        <h4 class="header-title"><?= $current->getLabel(); ?></h4>

        <?= $this->form()->openTag($form->setAttributes([
            'class' => 'form-horizontal',
            'role' => 'form'
        ])); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('firstname')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter user first name')
                ]),
            'label' => $this->translate('First Name'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('lastname')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter user last name')
                ]),
            'label' => $this->translate('Last Name')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('username')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter username')
                ]),
            'label' => $this->translate('Username')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('email')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter user email'),
                    'autocomplete' => 'off'
                ]),
            'label' => $this->translate('Email')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('password')
                ->setAttributes([
                    'placeholder' => $this->translate('Enter user password'),
                    'autocomplete' => 'off'
                ]),
            'label' => $this->translate('Password')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('confirm')
                ->setAttributes([
                    'placeholder' => $this->translate('Confirm user password'),
                    'autocomplete' => 'off'
                ]),
            'label' => $this->translate('Confirm')
        ]); ?>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="reset" class="btn btn-default">Reset</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>

