<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

use MSBios\Resource\Entity\User;

/** @var array $page */
$page = $this->navigation()->findActive(Navigation\Sidebar::class);

/** @var \Zend\Navigation\Page\Mvc $current */
$current = $page['page'];

?>
<div class="row">
    <div class="col-sm-12">
        <h4 class="header-title"><?= $current->getLabel(); ?></h4>

        <?php if (!$this->paginator->count()) : ?>

            <div class="alert alert-info" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no user, click "Add new entity" to start working with the user.'); ?></p>
                <p>
                    <a href="<?= $this->url($this->config->getRouteName(), [
                        'action' => 'add'
                    ]); ?>" class="btn btn-info"><?= $this->translate('Add new record'); ?></a>
                </p>
            </div>

        <?php else: ?>

            <?= $this->partial('partial/alert.phtml'); ?>

            <a href="<?= $this->url($this->config->getRouteName(), [
                'action' => 'add'
            ]); ?>" class="btn btn-success m-b-5"><?= $this->translate('Add new record'); ?></a>

            <button type="button" class="btn btn-danger m-b-5"
                    data-toggle="modal"
                    data-target="#modal-confirm-all"><?= $this->translate('Remove selected records'); ?>
            </button>

            <?= $this->form()->openTag(new \Zend\Form\Form); ?>

            <!-- Modal -->
            <div class="modal fade text-center"
                 id="modal-confirm-all"
                 tabindex="-1" role="dialog">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"><?= $this->translate('Are you sure?'); ?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?= $this->translate('Do you want to delete records?'); ?></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                <?= $this->translate('Cancel'); ?>
                            </button>
                            <button type="submit" class="btn btn-danger">
                                <?= $this->translate('Yes, delete them!'); ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                <thead>
                <tr>
                    <th style="width: 95px;">
                        <div class="checkbox checkbox-primary checkbox-single m-r-15">
                            <input id="action-checkbox-all" type="checkbox">
                            <label for="action-checkbox-all"></label>
                        </div>
                    </th>
                    <th><?= $this->translate('First Name'); ?></th>
                    <th><?= $this->translate('Last Name'); ?></th>
                    <th><?= $this->translate('Username'); ?></th>
                    <th width="50px"><?= $this->translate('Actions'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var User $item */ ?>
                <?php foreach ($this->paginator as $item): ?>
                    <tr>
                        <th scope="row">
                            <div class="checkbox checkbox-primary m-r-15">
                                <?php $identifier = "action-checkbox-{$item->getId()}"; ?>
                                <?= $this->formCheckbox(new \Zend\Form\Element\Checkbox("items[{$item->getId()}]", [
                                    'id' => $identifier
                                ])); ?>
                                <label for="<?= $identifier; ?>"></label>
                            </div>
                        </th>
                        <td><?= $this->escapeHtml($item->getFirstname()); ?></td>
                        <td><?= $this->escapeHtml($item->getLastname()); ?></td>
                        <td><?= $this->escapeHtml($item->getUsername()); ?></td>
                        <td class="text-center">
                            <a href="<?= $this->url($this->config->getRouteName(), [
                                'action' => 'edit',
                                'id' => $item->getId()
                            ]); ?>" class="btn btn-icon btn-primary btn-xs">
                                <i class="mdi mdi-pencil"></i>
                            </a>

                            <button type="button" class="btn btn-icon btn-danger btn-xs waves-effect waves-light"
                                    data-toggle="modal"
                                    data-target="#modal-confirm-<?= $item->getId(); ?>">
                                <i class="mdi mdi-delete"></i>
                            </button>

                            <!-- Modal -->
                            <div class="modal fade"
                                 id="modal-confirm-<?= $item->getId(); ?>"
                                 tabindex="-1" role="dialog">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Are you sure?</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Do you want to delete the entry?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                                Cancel
                                            </button>
                                            <a href="<?= $this->url($this->config->getRouteName(), [
                                                'action' => 'drop',
                                                'id' => $item->getId()
                                            ]); ?>" class="btn btn-primary">
                                                Yes, delete it!
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <?= $this->form()->closeTag(); ?>

            <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                'route' => $this->config->getRouteName()
            ]); ?>

        <?php endif; ?>


    </div> <!-- end col -->


</div>