<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Portal\CPanel;

/** @var \Zend\Form\ElementInterface $element */
$element = $this->element;
/** @var array $messages */
$messages = $element->getMessages();
/** @var boolean $hasError */
$hasError = count($messages);
?>
<div class="form-group <?php if ($hasError): ?>has-error has-feedback<?php endif; ?>">
    <label class="col-md-2 control-label" for="<?= $element->getName(); ?>">
        <?= $this->label; ?>:
        <?php if($element->hasAttribute('required')): ?>
            <span class="text-danger">*</span>
        <?php endif; ?>
    </label>
    <div class="col-md-10">
        <?= $this->formElement($element->setAttributes([
            'id' => $element->getName(),
            'class' => 'form-control'
        ])); ?>

        <?php if (count($messages)): ?>
            <span class="glyphicon glyphicon-remove form-control-feedback"></span>
            <span class="help-block">
                <?php foreach ($messages as $message): ?>
                    <small><?= $message; ?></small>
                <?php endforeach; ?>
            </span>
        <?php endif; ?>

    </div>
</div>