<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Portal\CPanel;
?>
<ul class="metisMenu nav" id="side-menu">

    <?php /** @var \Zend\Navigation\Page\Mvc $page */ ?>
    <?php foreach ($this->container as $page): ?>

        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>

        <?php $hasChildren = $page->hasPages(true); ?>
        <?php if (!$hasChildren): ?>

            <li class="<?php if ($page->isActive()): ?>active<?php endif; ?>">
                <a href="<?= $page->getHref(); ?>">
                    <i class="<?= $page->getClass(); ?>"></i>
                    <?= $this->translate($page->getLabel()); ?>
                </a>
            </li>
        <?php else: ?>

            <li class="<?php if ($page->isActive()): ?>active<?php endif; ?>">
                <a href="javascript: void(0);" aria-expanded="true">
                    <i class="<?= $page->getClass(); ?>"></i>
                    <?= $this->translate($page->getLabel()); ?>
                    <span class="fa arrow"></span>
                </a>

                <ul class="nav-second-level nav" aria-expanded="true">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if (!$child->isVisible() || !$this->navigation()->accept($page)) continue; ?>
                        <li class="<?php if ($child->isActive()): ?>active<?php endif; ?>">
                            <a href="<?= $child->getHref(); ?>">
                                <?= $this->translate($child->getLabel()); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>

            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
